### ISSUE TITLE
运行一段时间后总发生处理Ethereum消息超时

### ISSUE THREAD

**Issue by bailiyi** [FISCO-BCOS/web3sdk#33]
目前使用web3sdk生成的java代码和链交互。在正常使用一段时间后，就会发生“处理Ethereum消息超时”，此时重启链和java项目就会回复正常。请问这是什么原因，如何解决。
错误信息如下：
`2018-05-16 16:11:41.374 ERROR 19642 --- [tLoopGroup-2-11] org.bcos.channel.handler.ChannelHandler  : 网络错误

java.io.IOException: Connection reset by peer
at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_144]
at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_144]
at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_144]
at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_144]
at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_144]
at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-all-4.1.22.Final.jar:4.1.22.Final]
at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108) ~[netty-all-4.1.22.Final.jar:4.1.22.Final]
at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345) ~[netty-all-4.1.22.Final.jar:4.1.22.Final]
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) ~[netty-all-4.1.22.Final.jar:4.1.22.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [netty-all-4.1.22.Final.jar:4.1.22.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [netty-all-4.1.22.Final.jar:4.1.22.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [netty-all-4.1.22.Final.jar:4.1.22.Final]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-all-4.1.22.Final.jar:4.1.22.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [netty-all-4.1.22.Final.jar:4.1.22.Final]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.22.Final.jar:4.1.22.Final]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]

2018-05-16 16:11:43.390 ERROR 19642 --- [pool-2-thread-1] o.b.c.client.EthereumResponseCallback    : 处理Ethereum消息超时:{}
`

**Comment by fisco-dev** [comment]
已知的bug，可以合入这个PR：https://github.com/FISCO-BCOS/FISCO-BCOS/pull/78，之后会合入FISCO-BCOS
