### ISSUE TITLE
加载pem账号文件时报错

### ISSUE THREAD

**Issue by pengbs** [FISCO-BCOS/web3sdk#385]
加载本地.pem文件时报错，报错信息如下:`java.lang.ClassCastException: org.bouncycastle.jcajce.provider.asymmetric.ec.BCECPrivateKey cannot be cast to org.bouncycastle.jcajce.provider.asymmetric.ec.BCECPrivateKey
at org.fisco.bcos.web3j.crypto.ECKeyPair.create(ECKeyPair.java:52)
at org.fisco.bcos.web3j.crypto.Keys.createEcKeyPair(Keys.java:59)`

使用的是最新版的web3sdk, maven的方式依赖的

**Comment by ywy2090** [comment]
> 加载本地.pem文件时报错，报错信息如下:`java.lang.ClassCastException: org.bouncycastle.jcajce.provider.asymmetric.ec.BCECPrivateKey cannot be cast to org.bouncycastle.jcajce.provider.asymmetric.ec.BCECPrivateKey at org.fisco.bcos.web3j.crypto.ECKeyPair.create(ECKeyPair.java:52) at org.fisco.bcos.web3j.crypto.Keys.createEcKeyPair(Keys.java:59)`
> 
> 使用的是最新版的web3sdk, maven的方式依赖的

你看下你的依赖库的bcprov的版本，看看是不是版本冲突？

**Comment by pengbs** [comment]
版本没有冲突，我是在一个tomcat容器里面运行两个项目，两个项目都引用了web3sdk的情况下就会出现
