### ISSUE TITLE
启动测试类报错

### ISSUE THREAD

**Issue by Blackcatfish** [FISCO-BCOS/web3sdk#87]
java.lang.Exception: Init ChannelService fail!Please Refer To Link Below:https://github.com/FISCO-BCOS/web3sdk/wiki/web3sdk-debug
	at org.bcos.channel.client.Service.run(Service.java:242)
	at org.bcos.channel.test.PerfOk.main(PerfOk.java:33)

启动测试类都是报这个错   ca.crt和clien.keystore都已经cp下来了

**Comment by JimmyShi22** [comment]
参考这个链接：
https://github.com/FISCO-BCOS/web3sdk/wiki/web3sdk-debug
